from geomach_geometry import geomach_geometry
from conventional5 import Conventional5

import classes
from class_structure import grid
from class_structure import CTRIA3
from read_geomach_structural_file import read_geomach_structural_file
from visualize_geomach_geometry import visualize_geomach_geometry

from write_tecplot_file import write_tecplot_file